
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SMSClientIntf", targetNamespace = "http://sms/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSClientIntf {


    /**
     * 
     * @param message
     * @param recipient
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://sms/", className = "ws.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://sms/", className = "ws.SendMessageResponse")
    public int sendMessage(
        @WebParam(name = "recipient", targetNamespace = "")
        String recipient,
        @WebParam(name = "message", targetNamespace = "")
        String message);

}
