
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SMSClientService", targetNamespace = "http://sms/", wsdlLocation = "http://localhost:9090/MyWebService/sms?wsdl")
public class SMSClientService
    extends Service
{

    private final static URL SMSCLIENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.SMSClientService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.SMSClientService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9090/MyWebService/sms?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9090/MyWebService/sms?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SMSCLIENTSERVICE_WSDL_LOCATION = url;
    }

    public SMSClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSClientService() {
        super(SMSCLIENTSERVICE_WSDL_LOCATION, new QName("http://sms/", "SMSClientService"));
    }

    /**
     * 
     * @return
     *     returns SMSClientIntf
     */
    @WebEndpoint(name = "SMSClientPort")
    public SMSClientIntf getSMSClientPort() {
        return super.getPort(new QName("http://sms/", "SMSClientPort"), SMSClientIntf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSClientIntf
     */
    @WebEndpoint(name = "SMSClientPort")
    public SMSClientIntf getSMSClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sms/", "SMSClientPort"), SMSClientIntf.class, features);
    }

}
